title: 文月雨耀
#Comment out url when working locally to resolve base urls correctly
#url: https://robinzfrzf.github.io

# Owner/author information
owner:
  name: robinzfrzf
  avatar: robinzfrzf.png
  # bio: 
  email: robinzfrzf@gmail.com
  #cv: https://robinzfrzf.site/file/CV-robinzfrzf.pdf
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter: robinzfrzf
  github: robinzfrzf
  bilibili: 12630894
# Analytics and webmaster tools stuff goes here
# https://search.google.com/search-console/ownership
#google_verify: ""


# Links to include in top navigation
# For external links add external: true
links:
  - title: Home page
    url: /
  - title: Hobbies
    url: /hobbies/
  - title: Notes
    url: /notes/
  - title: Blogs
    url: /blogs/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: China/Beijing
future: true
highlighter: rouge
# markdown: kramdown
# markdown: redcarpet
# pygments: true


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  # coderay:
  #   coderay_line_numbers:
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class


# disqus settings:
disqus:
  shortname: robinzfrzf

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]
